services:
  - type: web
    name: three-player-chess
    env: static
    buildCommand: null  # No build needed for static site
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 